### ISSUE TITLE
MappingCouchbaseConverter.write() does not provide equivalent target for lists

### ISSUE THREAD

**Issue by vals-productions** [spring-projects/spring-data-couchbase#1540]
Simplified document:

```
@Document
public class Entity  {
...
	private List<EmailToken> tokenList = new LinkedList<>();

	public static class EmailToken {
		private String token;
		private String type; 
...
```

Saved through Repository the JSON looks like the following:

```
{
 ...
  "tokenList": [
    {
      "token": "G1LTUPAPVQ1JGGE",
      "type": "Type 1"
    }
  ]
... 
}
```

I wanted to try transaction stuff and tried to save the same object through the code suggested in docs:
[Transaction Support](https://docs.spring.io/spring-data/couchbase/docs/current/reference/html/#couchbase.transactions)
```
CouchbaseDocument entityDoc = new CouchbaseDocument(entity.getId());
mappingCouchbaseConverter.write(entity, entityDoc);
ctx.insert(
	couchbaseClientFactory.withScope("some scope").getCollection("someColl"), 
	entityDoc.getId()(), 
	entityDoc.getContent());

```
The result looks like the following:

```
{
...
  "tokenList": {
    "empty": false
  }
...
}
```

tokenList becomes a Map instead of a List with data loss.

**Comment by mikereiche** [comment]
Fixed in https://github.com/spring-projects/spring-data-couchbase/issues/868

Please use the latest version to avoid issues that have already been fixed.  The latest version is 4.4.2.  https://spring.io/projects/spring-data-couchbase

Couchbase Transactions are integrated into Spring Data Couchbase beginning in 5.0.0-M5 (prerelease milestone 5)

The transactions documentation which will appear in the next release (5.0.0-M6 at https://docs.spring.io/spring-data/couchbase/docs/5.0.0-M6/reference/html/#couchbase.transactions) is currently staged at https://mikereiche.github.io/staged/ (look for the Transactions section).

There are all kinds of examples spring-data-couchbase/src/test/java in : git clone [git@github.com](mailto:git@github.com):spring-projects/spring-data-couchbase.git. (search for test cases with 'Transaction' in the name).

**Comment by vals-productions** [comment]
I was using 4.4.0 that was supposed to have the fix. Upgraded to 4.4.2 but still get the issue. I also reproduced the issue 
with List<Map<>> data structure mentioned as fixed in https://github.com/spring-projects/spring-data-couchbase/issues/868 .

I think that maybe the issue was re-introduced or not transferred into collections? As 4.0.2 is pre-collections release.

**Comment by mikereiche** [comment]
can you give a link to your github project?
